### ISSUE TITLE
RuntimeError: cuda runtime error (9)

### ISSUE THREAD

**Issue by bxiang233** [Jia-Research-Lab/PointGroup#30]
Dear Li Jiang,

Thanks a lot for your great work!
I successfully ran the training code, but when I run "python test.py --config config/pointgroup_run1_scannet.yaml", I got an error as following:

/cluster/scratch/bxiang/PointGroup/util/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[2020-12-12 23:02:48,713  INFO  log.py  line 40  12439]  ************************ Start Logging ************************
[2020-12-12 23:02:49,155  INFO  test.py  line 32  12439]  Namespace(TEST_NMS_THRESH=0.3, TEST_NPOINT_THRESH=100, TEST_SCORE_THRESH=0.09, batch_size=4, bg_thresh=0.25, block_reps=2, block_residual=True, classes=20, cluster_meanActive=50, cluster_npoint_thre=50, cluster_radius=0.03, cluster_shift_meanActive=300, config='config/pointgroup_run1_scannet.yaml', data_root='dataset', dataset='scannetv2', dataset_dir='data/scannetv2_inst.py', epochs=384, eval=True, exp_path='exp/scannetv2/pointgroup/pointgroup_run1_scannet', fg_thresh=0.75, filename_suffix='_inst_nostuff.pth', fix_module=[], full_scale=[128, 512], ignore_label=-100, input_channel=3, loss_weight=[1.0, 1.0, 1.0, 1.0], lr=0.001, m=16, manual_seed=123, max_npoint=250000, mode=4, model_dir='model/pointgroup/pointgroup.py', model_name='pointgroup', momentum=0.9, multiplier=0.5, optim='Adam', prepare_epochs=128, pretrain='', pretrain_module=[], pretrain_path=None, save_freq=16, save_instance=False, save_pt_offsets=False, save_semantic=False, scale=50, score_fullscale=14, score_mode=4, score_scale=50, split='val', step_epoch=384, task='test', test_epoch=182, test_seed=567, test_workers=16, train_workers=16, use_coords=True, weight_decay=0.0001)
[2020-12-12 23:02:49,158  INFO  test.py  line 188  12439]  => creating model ...
[2020-12-12 23:02:49,159  INFO  test.py  line 189  12439]  Classes: 20
[2020-12-12 23:02:49,791  INFO  test.py  line 200  12439]  cuda available: True
[2020-12-12 23:02:57,609  INFO  test.py  line 205  12439]  #classifier parameters (model): 7715016
[2020-12-12 23:02:57,650  INFO  utils.py  line 63  12439]  Restore from exp/scannetv2/pointgroup/pointgroup_run1_scannet/pointgroup_run1_scannet-000000182.pth
[2020-12-12 23:02:58,077  INFO  test.py  line 41  12439]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2020-12-12 23:03:56,509  INFO  scannetv2_inst.py  line 65  12439]  Testing samples (val): 312
exp/scannetv2/pointgroup/pointgroup_run1_scannet
pointgroup_run1_scannet
[2020-12-12 23:04:02,410  INFO  test.py  line 157  12439]  instance iter: 1/312 point_num: 237360 ncluster: 25 time: total 5.90s inference 0.68s save 0.00s
[2020-12-12 23:04:03,179  INFO  test.py  line 157  12439]  instance iter: 2/312 point_num: 239261 ncluster: 27 time: total 0.77s inference 0.51s save 0.00s
[2020-12-12 23:04:03,852  INFO  test.py  line 157  12439]  instance iter: 3/312 point_num: 217086 ncluster: 24 time: total 0.67s inference 0.41s save 0.00s
...........
...........
...........
[2020-12-12 23:05:44,345  INFO  test.py  line 157  12439]  instance iter: 253/312 point_num: 100286 ncluster: 11 time: total 0.43s inference 0.21s save 0.00s
[2020-12-12 23:05:44,831  INFO  test.py  line 157  12439]  instance iter: 254/312 point_num: 284951 ncluster: 20 time: total 0.49s inference 0.32s save 0.00s
[2020-12-12 23:05:45,443  INFO  test.py  line 157  12439]  instance iter: 255/312 point_num: 331565 ncluster: 19 time: total 0.61s inference 0.36s save 0.00s
[2020-12-12 23:05:45,739  INFO  test.py  line 157  12439]  instance iter: 256/312 point_num: 139138 ncluster: 9 time: total 0.30s inference 0.21s save 0.00s
[2020-12-12 23:05:46,136  INFO  test.py  line 157  12439]  instance iter: 257/312 point_num: 159475 ncluster: 24 time: total 0.40s inference 0.22s save 0.00s
[2020-12-12 23:05:46,485  INFO  test.py  line 157  12439]  instance iter: 258/312 point_num: 133857 ncluster: 10 time: total 0.35s inference 0.23s save 0.00s
[2020-12-12 23:05:46,776  INFO  test.py  line 157  12439]  instance iter: 259/312 point_num: 129951 ncluster: 6 time: total 0.29s inference 0.22s save 0.00s
[2020-12-12 23:05:47,052  INFO  test.py  line 157  12439]  instance iter: 260/312 point_num: 110960 ncluster: 7 time: total 0.28s inference 0.22s save 0.00s
[2020-12-12 23:05:47,452  INFO  test.py  line 157  12439]  instance iter: 261/312 point_num: 184428 ncluster: 14 time: total 0.40s inference 0.30s save 0.00s
[2020-12-12 23:05:47,903  INFO  test.py  line 157  12439]  instance iter: 262/312 point_num: 258402 ncluster: 13 time: total 0.45s inference 0.29s save 0.00s
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMath.cu line=35 error=9 : invalid configuration argument
Traceback (most recent call last):
  File "test.py", line 214, in <module>
    test(model, model_fn, data_name, cfg.test_epoch)
  File "test.py", line 63, in test
    preds = model_fn(batch, model, epoch)
  File "/cluster/scratch/bxiang/PointGroup/model/pointgroup/pointgroup.py", line 351, in test_model_fn
    ret = model(input_, p2v_map, coords_float, coords[:, 0].int(), batch_offsets, epoch)
  File "/cluster/home/bxiang/miniconda3/envs/pointgroup/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/scratch/bxiang/PointGroup/model/pointgroup/pointgroup.py", line 310, in forward
    input_feats, inp_map = self.clusters_voxelization(proposals_idx, proposals_offset, output_feats, coords, self.score_fullscale, self.score_scale, self.mode)
  File "/cluster/scratch/bxiang/PointGroup/model/pointgroup/pointgroup.py", line 220, in clusters_voxelization
    clusters_coords_min = pointgroup_ops.sec_min(clusters_coords, clusters_offset.cuda())  # (nCluster, 3), float
  File "/cluster/scratch/bxiang/PointGroup/lib/pointgroup_ops/functions/pointgroup_ops.py", line 299, in forward
    out = torch.cuda.FloatTensor(nProposal, C).zero_()
RuntimeError: cuda runtime error (9) : invalid configuration argument at /pytorch/aten/src/THC/generic/THCTensorMath.cu:35

Could you please give me some idea about what is the problem and how to fix it? Thanks a lot!

**Comment by KularatnaS** [comment]
I also ran in to the same error. Did you manage to find a solution to this?

**Comment by bxiang233** [comment]
> I also ran in to the same error. Did you manage to find a solution to this?

No, I still have not figured it out. Sorry.
