### ISSUE TITLE
RuntimeError: cublas runtime error

### ISSUE THREAD

**Issue by HelinXu** [Jia-Research-Lab/PointGroup#50]
Hi all,

Did anyone use 2080 Ti for this project?

## environment

- 2080 Ti
- python 3.7.0
- pytorch 1.1.0
- CUDA 9.0
- gcc 5.4

I set up the project exactly as suggested in README, prepared the data properly, but received this error when running the default train scripy:

```shell
$ CUDA_VISIBLE_DEVICES=0 python train.py --config config/pointgroup_run1_scannet.yaml 

/data2/helin/1/PointGroup/util/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[2021-09-04 20:51:03,613  INFO  log.py  line 40  907024]  ************************ Start Logging ************************
[2021-09-04 20:51:03,641  INFO  train.py  line 26  907024]  Namespace(TEST_NMS_THRESH=0.3, TEST_NPOINT_THRESH=100, TEST_SCORE_THRESH=0.09, batch_size=4, bg_thresh=0.25, block_reps=2, block_residual=True, classes=22, cluster_meanActive=50, cluster_npoint_thre=50, cluster_radius=0.03, cluster_shift_meanActive=300, config='config/pointgroup_run1_scannet.yaml', data_root='dataset', dataset='scannetv2', dataset_dir='data/scannetv2_inst.py', epochs=384, eval=True, exp_path='exp/scannetv2/pointgroup/pointgroup_run1_scannet', fg_thresh=0.75, filename_suffix='_inst_nostuff.pth', fix_module=[], full_scale=[128, 512], ignore_label=-100, input_channel=3, loss_weight=[1.0, 1.0, 1.0, 1.0], lr=0.001, m=16, manual_seed=123, max_npoint=250000, mode=4, model_dir='model/pointgroup/pointgroup.py', model_name='pointgroup', momentum=0.9, multiplier=0.5, optim='Adam', prepare_epochs=128, pretrain='', pretrain_module=[], pretrain_path=None, save_freq=16, save_instance=False, save_pt_offsets=False, save_semantic=False, scale=50, score_fullscale=14, score_mode=4, score_scale=50, split='val', step_epoch=384, task='train', test_epoch=384, test_seed=567, test_workers=16, train_workers=16, use_coords=True, weight_decay=0.0001)
[2021-09-04 20:51:03,648  INFO  train.py  line 135  907024]  => creating model ...
[2021-09-04 20:51:03,946  INFO  train.py  line 148  907024]  cuda available: False
[2021-09-04 20:51:08,453  INFO  train.py  line 153  907024]  #classifier parameters: 7715050
[2021-09-04 20:51:08,759  INFO  scannetv2_inst.py  line 43  907024]  Training samples: 4
[2021-09-04 20:51:08,784  INFO  scannetv2_inst.py  line 54  907024]  Validation samples: 1
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    train_epoch(dataset.train_data_loader, model, model_fn, optimizer, epoch)
  File "train.py", line 54, in train_epoch
    loss, _, visual_dict, meter_dict = model_fn(batch, model, epoch)
  File "/data2/helin/1/PointGroup/model/pointgroup/pointgroup.py", line 398, in model_fn
    ret = model(input_, p2v_map, coords_float, coords[:, 0].int(), batch_offsets, epoch)
  File "/home/helinxu/anaconda3/envs/pointgroup2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/helin/1/PointGroup/model/pointgroup/pointgroup.py", line 264, in forward
    output = self.input_conv(input)
  File "/home/helinxu/anaconda3/envs/pointgroup2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/helinxu/anaconda3/envs/pointgroup2/lib/python3.7/site-packages/spconv/modules.py", line 123, in forward
    input = module(input)
  File "/home/helinxu/anaconda3/envs/pointgroup2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/helinxu/anaconda3/envs/pointgroup2/lib/python3.7/site-packages/spconv/conv.py", line 157, in forward
    outids.shape[0])
  File "/home/helinxu/anaconda3/envs/pointgroup2/lib/python3.7/site-packages/spconv/functional.py", line 83, in forward
    return ops.indice_conv(features, filters, indice_pairs, indice_pair_num, num_activate_out, False, True)
  File "/home/helinxu/anaconda3/envs/pointgroup2/lib/python3.7/site-packages/spconv/ops.py", line 112, in indice_conv
    int(inverse), int(subm))
RuntimeError: cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-cbsmv48q/aten/src/THC/THCBlas.cu:259
```

I looked up the error message `RuntimeError: cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-cbsmv48q/aten/src/THC/THCBlas.cu:259` a bit, and I suppose it has something to do with the GPU version I am using, which is 2080 Ti. (However, I'm not quit sure about that, it may have been caused by other reasons.)

Could anyone give me some suggestions? Plus, what GPU are you using to get it through?

Thanks!

**Comment by HelinXu** [comment]
I got it through.

- CUDA 10.0
- pytorch 1.1.0 (conda installed)
- cudnn 7.6.5

- CUDA 9.0 may not work with 2080 Ti on this project. Previous issues here have mentioned this: https://github.com/dvlab-research/PointGroup/issues/1#issuecomment-629102256.
- I got tons of errors when trying to compile with CUDA 10.0, but they were all fixable. 
- Here's a few errors I received: `libstdc++.so.6: version 'GLIBCXX_3.4.22' not found` solved by replacing libstdc++.so.6 by copying from `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`. Useful commands: `strings /path/to/libstdc++.so.6 | grep GLIBCXX` returns the GLIBCXX versions that exist. In my case:

```shell
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

You can see the missing `GLIBCXX_3.4.22` can be found here.

- Others errors were solved by #48.
