### ISSUE TITLE
error running ' python setup.py bdist_wheel'

### ISSUE THREAD

**Issue by Shegun93** [Jia-Research-Lab/PointGroup#55]
It awesome seeing amazing work you did.
I have been trying to follow the instructions for the reimplementation of your work but having a problem running `python setup.py bdist_wheel` please help take a look what i was missing.

here's my log

(pointgroup) segun@segun-HP-Pavilion-Notebook:~/PointGroup/lib/spconv$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
/home/segun/PointGroup/lib/spconv/build/lib.linux-x86_64-3.7
Release
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.1
CMake Warning (dev) at /home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/cmake/data/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (CUDNN) does
  not match the name of the calling package (Caffe2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:107 (find_package_handle_standard_args)
  /home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:23 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found cuDNN: v7.6.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  5.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_50,code=sm_50
CMake Warning (dev) at /home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/cmake/data/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- pybind11 v2.3.dev0
-- Configuring done
CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/segun/PointGroup/lib/spconv/build/temp.linux-x86_64-3.7
Consolidate compiler generated dependencies of target spconv_nms
Consolidate compiler generated dependencies of target spconv
[ 15%] Built target spconv_nms
[ 23%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 92%] Built target spconv
In file included from /home/segun/PointGroup/lib/spconv/src/utils/all.cc:15:0:
/home/segun/PointGroup/lib/spconv/include/spconv/nms.h:20:10: fatal error: boost/geometry.hpp: No such file or directory
 #include <boost/geometry.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/utils/CMakeFiles/spconv_utils.dir/build.make:75: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all.cc.o' failed
make[2]: *** [src/utils/CMakeFiles/spconv_utils.dir/all.cc.o] Error 1
CMakeFiles/Makefile2:187: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all' failed
make[1]: *** [src/utils/CMakeFiles/spconv_utils.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/segun/anaconda3/envs/pointgroup/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by zoomin-lee** [comment]
Hi, how did you solve it?

**Comment by zyjhxd** [comment]
> a
请问解决了吗
